// Generated by CoffeeScript 1.9.1
(function() {
  var $, displayHighlights, highlight, numberAsText, removeAllHighlights;

  $ = jQuery;

  numberAsText = function(n) {
    switch (n) {
      case 1:
        return "one";
      case 2:
        return "two";
      case 3:
        return "three";
      case 4:
        return "four";
      case 5:
        return "five";
      case 6:
        return "six";
      case 7:
        return "seven";
      case 8:
        return "eight";
      case 9:
        return "nine";
      case 10:
        return "ten";
      case 11:
        return "eleven";
      case 12:
      case 0:
        return "twelve";
    }
  };

  highlight = function(selector) {
    return $("#" + selector).addClass("white");
  };

  removeAllHighlights = function() {
    return $(".clock-text span").removeClass("white");
  };

  displayHighlights = function() {
    var date, hours, minutes, oclock, to;
    highlight("itis");
    date = new Date();
    hours = date.getHours();
    minutes = date.getMinutes();
    to = false;
    oclock = false;
    if (hours >= 12) {
      hours -= 12;
    }
    if (minutes >= 33) {
      to = true;
      hours++;
    }
    highlight("" + (numberAsText(hours)));
    if ((minutes >= 0 && minutes <= 2) || (minutes >= 58 && minutes <= 59)) {
      oclock = true;
    }
    if ((minutes >= 3 && minutes <= 7) || (minutes >= 53 && minutes <= 57)) {
      highlight("five-past-to");
    }
    if ((minutes >= 8 && minutes <= 12) || (minutes >= 48 && minutes <= 52)) {
      highlight("ten-past-to");
    }
    if ((minutes >= 13 && minutes <= 17) || (minutes >= 43 && minutes <= 47)) {
      highlight("quarter-past-to");
    }
    if ((minutes >= 18 && minutes <= 22) || (minutes >= 38 && minutes <= 42)) {
      highlight("twenty-past-to");
    }
    if ((minutes >= 23 && minutes <= 27) || (minutes >= 33 && minutes <= 37)) {
      highlight("twenty-five-past-to");
    }
    if (minutes >= 28 && minutes <= 32) {
      highlight("half-past-to");
    }
    if (oclock) {
      return highlight("oclock");
    } else if (to) {
      return highlight("to");
    } else {
      return highlight("past");
    }
  };

  displayHighlights();

  setInterval(function() {
    removeAllHighlights();
    return displayHighlights();
  }, 5000);

}).call(this);
